pipeline
{
    agent none

    stages {
        stage('build') {
            steps {
                echo 'this is build stage'
            }
        }

        stage('Test') {
            steps {
                echo 'this is test stage'
            }
        }

        stage('Deliver') {
            steps {
                echo 'this is deliver stage'
            }
        }
    }
}
