pipeline
{
    agent {
        label 'devServer'
    }
    tools {
        maven 'maven'
    }

    stages {
        stage('build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
    post {
        success {
            echo 'the job is successful'
            archiveArtifacts artifacts: 'target/*.war', fingerprint: true
        }
    }
}
